// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('foxtailArtisanrycomApp').controller('AdminDashboardCtrl', function($scope, $http, $location, Auth, fileUpload, adminBidiSocket) {
  $scope.processing = null;
  $scope.updating = null;
  $scope.rebuilding = null;
  $scope.restarting = null;
  $scope.console = '';
  $http.get('/api/users/me').success(function(user) {
    return $scope.user = user;
  });
  $scope.logout = function() {
    console.log("What is this I don't even.");
    return Auth.logout().then(function() {
      return $location.path("/admin/login");
    });
  };
  $scope.submitFile = function() {
    var file, uploadUrl;
    console.log('submitFile');
    file = $scope.dataFile;
    uploadUrl = '/api/acceptFile';
    return fileUpload.uploadFileToUrl(file, uploadUrl, function(err, msg) {
      $scope.message = '';
      $scope.processing = null;
      if (err != null) {
        $scope.message = 'ERROR: ';
      }
      return $scope.message = msg;
    });
  };
  $scope.updateWebsite = function() {
    $scope.updating = true;
    return $http.get('/api/updateWebsite').success(function(data) {
      $scope.message = "Website update done. (" + data + ")";
      return $scope.updating = null;
    }).error(function(error, status) {
      $scope.message = "Website update failed: " + status + " - " + error;
      return $scope.updating = null;
    });
  };
  $scope.buildWebsite = function() {
    $scope.rebuilding = true;
    return $http.get('/api/buildWebsite').success(function(data) {
      $scope.message = "Website build done. (" + data + ")";
      return $scope.rebuilding = null;
    }).error(function(error, status) {
      $scope.message = "Website build failed: " + status + " - " + error;
      return $scope.rebuilding = null;
    });
  };
  $scope.stopWebsite = function() {
    $scope.restarting = true;
    return $http.get('/api/stopWebsite').success(function(data) {
      $scope.message = "Website stopping... (" + data + ")";
      return $scope.restarting = null;
    }).error(function(error, status) {
      $scope.message = "Website stop failed: " + status + " - " + error;
      return $scope.restarting = null;
    });
  };
  adminBidiSocket.on('console', function(data, cb) {
    console.log("adminBidiSocket: " + data);
    if (typeof data !== 'undefined') {
      $scope.console += data;
    }
    if (typeof cb === "function") {
      return cb();
    }
  });
  return $http.get('/api/products/total').success(function(reply) {
    return $scope.numProducts = reply.numProducts;
  });
});
