// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('foxtailArtisanrycomApp').controller('ContactCtrl', function($scope, $http, $timeout, vcRecaptchaService) {
  $scope.model = '6LcAau8SAAAAAHbp1JcrJ243f4U5kDAzGRuDpXYP';
  return $scope.sendMessage = function() {
    return console.dir(vcRecaptchaService.data());
  };
});
