// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('foxtailArtisanrycomApp').controller('ContactCtrl', function($scope, $http, $timeout, vcRecaptchaService, $location) {
  $scope.reCAPTCHA = {
    key: '6LcAau8SAAAAAHbp1JcrJ2434U5kDAzGRuDpXYPf'
  };
  return $scope.sendMessage = function() {
    var data;
    data = vcRecaptchaService.data();
    data.name = $scope.name;
    data.email = $scope.email;
    data.message = $scope.message;
    if (typeof data.name === 'undefined' || typeof data.email === 'undefined' || typeof data.message === 'undefined') {
      return $scope.errormsg = 'Please fill in all fields.';
    }
    return $http.post('/api/contact', data).success(function(wat) {
      return $location.url('/contact-ok');
    }).error(function(wat) {
      return $scope.errormsg = wat;
    });
  };
});
